# Generated by Django 5.1.6 on 2025-03-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
