# Generated by Django 5.1.6 on 2025-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingsessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
