# Generated by Django 5.1.6 on 2025-04-18 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chathead_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participant_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participant_2',
        ),
    ]
