# Generated by Django 5.1.6 on 2025-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
          ("chat", "0001_initial"),  # or whatever the latest migration before 0002 was
      ]


    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS chat_chat CASCADE;")
    ]