# Generated by Django 5.1.6 on 2025-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_chathead_id_chat_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_int_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
