# Generated by Django 5.1.6 on 2025-04-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_chat_id_chat_chat_int_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_int_id',
            new_name='chat_id',
        ),
    ]
