# Generated by Django 5.1.6 on 2025-03-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_password_change',
        ),
    ]
