# Generated by Django 5.1.6 on 2025-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_dob_user_height_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('cm', 'Centimeters'), ('inches', 'Inches')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], max_length=10, null=True),
        ),
    ]
