# Generated by Django 5.1.6 on 2025-04-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_height_unit_user_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='performance_statistics',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
